[update_manager bambufy]
type: git_repo
channel: stable
path: /root/printer_data/config/mod_data/plugins/bambufy
origin: https://github.com/function3d/bambufy.git
is_system_service: False
primary_branch: master

[update_manager lessWaste]
type: git_repo
channel: stable
path: /root/printer_data/config/mod_data/plugins/lessWaste
origin: https://github.com/Hrybmo/lessWaste.git
is_system_service: False
primary_branch: master
