[update_manager bambufy]
type: git_repo
channel: stable
path: /root/printer_data/config/mod_data/plugins/bambufy
origin: https://github.com/function3d/bambufy.git
is_system_service: False
primary_branch: master

[update_manager lesswaste]
type: git_repo
channel: stable
path: /root/printer_data/config/mod_data/plugins/lesswaste
origin: https://github.com/Hrybmo/lesswaste.git
is_system_service: False
primary_branch: master
