#!/bin/sh
# (C) 2024-2026 ghzserg https://github.com/ghzserg/zmod
#
# Start guppyscreen
#

GUPPYSCREEN=/root/guppyscreen/guppyscreen
PID_FILE=/run/guppyscreen.pid
NICENESS=10

start() {
    source /opt/config/mod/.shell/0.sh
    xzcat /opt/config/mod/.shell/screen_off.raw.xz > /dev/fb0
    [ ${AD5X} -eq 0 ] && backlight 0

    TSNAME="Touchscreen"
    EVENT=event0
    for i in 0 1 2 3; do
        file=/sys/class/input/event$i/device/name
            for name in `cat $file`; do
                echo $name
            done
            if [ "$name" == $TSNAME ];then
               EVENT=event$i
               break;
            fi
    done

    export TSLIB_TSDEVICE=/dev/input/$EVENT
    export TSLIB_PLUGINDIR=/usr/lib/ts
    export TSLIB_CONFFILE=/etc/ts.conf
    export TSLIB_CALIBFILE=/etc/pointercal
    export TSLIB_FBDEVICE=/dev/fb0

    if [ "${ZLANG}" != 'ru' ]; then
        sed -i 's/Экструдер/Extruder/' /opt/config/mod_data/guppyconfig.json
        sed -i 's/Стол/Bed/' /opt/config/mod_data/guppyconfig.json
        sed -i 's/Голова/Head/' /opt/config/mod_data/guppyconfig.json
        sed -i 's/Вес/Weight/' /opt/config/mod_data/guppyconfig.json
    else
        sed -i 's/Extruder/Экструдер/' /opt/config/mod_data/guppyconfig.json
        sed -i 's/Head/Голова/' /opt/config/mod_data/guppyconfig.json
        sed -i 's/Bed/Стол/' /opt/config/mod_data/guppyconfig.json
        sed -i 's/Weight/Вес/' /opt/config/mod_data/guppyconfig.json
    fi

    mv /opt/config/mod_data/log/guppyscreen.4.log /opt/config/mod_data/log/guppyscreen.5.log
    mv /opt/config/mod_data/log/guppyscreen.3.log /opt/config/mod_data/log/guppyscreen.4.log
    mv /opt/config/mod_data/log/guppyscreen.2.log /opt/config/mod_data/log/guppyscreen.3.log
    mv /opt/config/mod_data/log/guppyscreen.1.log /opt/config/mod_data/log/guppyscreen.2.log
    mv /opt/config/mod_data/log/guppyscreen.log /opt/config/mod_data/log/guppyscreen.1.log

    killall guppyscreen
    [ ${AD5X} -eq 0 ] && backlight 60

    if [ "${ZLANG}" == "ja" ] || [ "${ZLANG}" == "ko" ] || [ "${ZLANG}" == "zh" ]; then
        export LANG="en_US.utf8"
    else
        export LANG=$(ls /usr/lib/locale | grep -i "^${ZLANG}" | head -n1)
    fi

    start-stop-daemon -S -b -m -p $PID_FILE -N $NICENESS --exec $GUPPYSCREEN
}

stop() {
    killall guppyscreen
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start &> /opt/config/mod_data/log/guppyscreen_start.log
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
