#!/bin/sh
#
# Start guppyscreen
#

source /opt/config/mod/.shell/0.sh

GUPPYSCREEN=/root/guppyscreen/guppyscreen
PID_FILE=/run/guppyscreen.pid
NICENESS=10

start() {
    [ ${FF5X} -eq 0 ] && backlight 0
    xzcat /opt/config/mod/.shell/screen_off.raw.xz > /dev/fb0

    mv /opt/config/mod_data/log/guppyscreen.4.log /opt/config/mod_data/log/guppyscreen.5.log
    mv /opt/config/mod_data/log/guppyscreen.3.log /opt/config/mod_data/log/guppyscreen.4.log
    mv /opt/config/mod_data/log/guppyscreen.2.log /opt/config/mod_data/log/guppyscreen.3.log
    mv /opt/config/mod_data/log/guppyscreen.1.log /opt/config/mod_data/log/guppyscreen.2.log
    mv /opt/config/mod_data/log/guppyscreen.log /opt/config/mod_data/log/guppyscreen.1.log

    /etc/init.d/S35tslib start
    killall guppyscreen
    start-stop-daemon -S -b -m -p $PID_FILE -N $NICENESS --exec /bin/sh -- -c $GUPPYSCREEN
    [ ${FF5X} -eq 0 ] && backlight 60
}

stop() {
    /etc/init.d/S35tslib stop
    killall guppyscreen
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start &> /opt/config/mod_data/log/guppyscreen_start.log
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
