#!/bin/sh
# (C) 2024-2026 ghzserg https://github.com/ghzserg/zmod

if [ $1 == "systemctl" ] || [ $1 == "sudo" ]; then
    [ $2 == "reboot" ] && echo "REBOOT" >/tmp/printer
    [ $2 == "poweroff" ] && echo "SHUTDOWN" >/tmp/printer
fi
