#!/bin/sh
#
# Start Camera
#

set -x
MOD=/data/.mod/.zmod

if ! [ -f /opt/config/mod_data/camera.conf ]
    then
        /root/printer_data/scripts/zcamera.sh off 640 480 20 video0 NOTRESTART
fi

VIDEO="video0"
source /opt/config/mod_data/camera.conf
PID_FILE=/run/camera.pid

start() {
    if [ $START = "on" ]
        then
            v4l2-ctl -d $VIDEO --list-formats
            if v4l2-ctl -d /dev/video0  --list-formats | grep MJPG; then
                /usr/bin/v4l2-ctl --set-fmt-video=width=${WIDTH},height=${HEIGHT},pixelformat=1
                if [ -f /THIS_IS_NOT_YOUR_ROOT_FILESYSTEM ]; then
                    start-stop-daemon -S -b -m -p $PID_FILE --exec /opt/config/mod/.shell/eabi/mjpg_streamer -- -o "/opt/config/mod/.shell/eabi/lib/output_http.so -w /opt/mjpg-streamer/www -p 8080" -i  "/opt/config/mod/.shell/eabi/lib/input_uvc.so -b 1 -d /dev/${VIDEO} -r ${WIDTH}x${HEIGHT} -f $FPS -fs $(( ${WIDTH} * ${HEIGHT} * 2 ))"
                else
                    start-stop-daemon -S -b -m -p $PID_FILE --exec /usr/bin/mjpg_streamer -- -o "/usr/lib/mjpg-streamer/output_http.so -w /usr/share/mjpg-streamer/www -p 8080" -i  "/usr/lib/mjpg-streamer/input_uvc.so -b 1 -d /dev/${VIDEO} -r ${WIDTH}x${HEIGHT} -f $FPS -fs $(( ${WIDTH} * ${HEIGHT} * 2 ))"
                fi
            else
                FORMAT=$(v4l2-ctl -d $VIDEO --list-formats| grep '\[' | tail -1| cut -d "'" -f2)
                if [ -f /THIS_IS_NOT_YOUR_ROOT_FILESYSTEM ]; then
                    while ! umount /data/.mod/; do
                        sleep 5
                    done
                    chroot $MOD start-stop-daemon -S -b -m -p $PID_FILE --exec /bin/ustreamer -- -d /dev/${VIDEO} -r ${WIDTH}x${HEIGHT} -f $FPS --format=$FORMAT -s 0.0.0.0
                    mount --bind /data/lost+found /data/.mod
                else
                    start-stop-daemon -S -b -m -p $PID_FILE --exec /bin/ustreamer -- -d /dev/${VIDEO} -r ${WIDTH}x${HEIGHT} -f $FPS --format=$FORMAT -s 0.0.0.0
                fi
            fi
        else
            echo "Камера отключена"
    fi
}

stop() {
    start-stop-daemon -K -p $PID_FILE 2>/dev/null >/dev/null
    killall mjpg_streamer ustreamer
}
restart() {
    stop
    sleep 2
    start
}

case "$1" in
  start)
        start &>/opt/config/mod_data/log/camera.log
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
