#!/bin/sh
#
# Camera config
#

if [ $# -ne 7 ]; then echo "Используйте $0 START WIDTH HEIGHT FPS VIDEO RESTART FS"; exit 1; fi

echo "# Do not edit this file
#
# If the camera is on, disable the camera on the printer screen
# If you need to restart the camera, use the CAMERA_RESTART macro
#
# Не редактируйте этот файл
#
# Если камера включена, то отключите камеру на экране принтера
# Если нужно перезапустить камеру, используйте макрос CAMERA_RESTART
#
# Используйте макрос
# Use a macro:
#
# CAMERA_ON WIDTH=$2 HEIGHT=$3 FPS=$4 VIDEO=$5 FS=$6
# CAMERA_OFF WIDTH=$2 HEIGHT=$3 FPS=$4 VIDEO=$5 FS=$6

# Start camera (on|off)
# Запускать камеру (on|off)
START=$1

# Resolution width: 1280
# Разрешение ширина: 1280
WIDTH=$2

# Resolution height: 720
# Разрешение высота: 720
HEIGHT=$3

# Frames per second: 15
# Кадров в секунду: 15
FPS=$4

# Video device: video0
# Видео устройство: video0
VIDEO=$5

# Trim memory on glitchy cameras (0-no, 1-yes)
# Обрезать память на глючных камерах (0-нет, 1-да)
FS=$6
" >/opt/config/mod_data/camera.conf

[ $7 = "RESTART" ] && /opt/config/mod/.shell/S99camera restart
